//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.01 at 10:17:26 AM IST 
//


package com.sample.Accessories.webservices.LeaseEligibility;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LeaseInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LeaseInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="contractName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractTerm" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="downPayment" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="monthlyInstallment" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LeaseInfoType", propOrder = {
    "contractName",
    "contractTerm",
    "downPayment",
    "monthlyInstallment"
})
public class LeaseInfoType {

    @XmlElement(required = true)
    protected String contractName;
    protected int contractTerm;
    protected double downPayment;
    protected double monthlyInstallment;

    /**
     * Gets the value of the contractName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * Sets the value of the contractName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractName(String value) {
        this.contractName = value;
    }

    /**
     * Gets the value of the contractTerm property.
     * 
     */
    public int getContractTerm() {
        return contractTerm;
    }

    /**
     * Sets the value of the contractTerm property.
     * 
     */
    public void setContractTerm(int value) {
        this.contractTerm = value;
    }

    /**
     * Gets the value of the downPayment property.
     * 
     */
    public double getDownPayment() {
        return downPayment;
    }

    /**
     * Sets the value of the downPayment property.
     * 
     */
    public void setDownPayment(double value) {
        this.downPayment = value;
    }

    /**
     * Gets the value of the monthlyInstallment property.
     * 
     */
    public double getMonthlyInstallment() {
        return monthlyInstallment;
    }

    /**
     * Sets the value of the monthlyInstallment property.
     * 
     */
    public void setMonthlyInstallment(double value) {
        this.monthlyInstallment = value;
    }

}
